# Generated by Django 4.1.5 on 2023-01-25 08:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=255)),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('category', models.CharField(choices=[('TK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('TG', 'Торговцы'), ('CM', 'Гилдмастеры'), ('KW', 'Квестгиверы'), ('KZ', 'Кузнецы'), ('KZH', 'Кожевники'), ('ZL', 'Зельевары'), ('MT', 'Мастера заклинаний')], default='TK', max_length=3)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ManyToManyField(blank=True, max_length=255, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Создать объявление',
                'verbose_name_plural': 'Создать объявления',
            },
        ),
    ]
